<?php

class Moto extends Vehicle {
	private $cylindree;
	
	const wheel_number = 2;
	public function __construct( $var1, $var2, $var3 ) {
		parent::__construct( $var1, $var2 );
		
		$this->cylindree = $var3;
	}
	
	public function getMotor() {
		return parent::getMotor() . " " .$this->cylindree  ; // TODO: Change the autogenerated stub
	}
}